:Author: ard12sgf1960
:Email: sgfpcb@gmail.com
:Date: 18/12/2023
:Revision: version 1.0
:License: Public Domain

= Project: {Project}

Connecting a GIGA R1 with Display Shield to Arduino IOT
Using LVGL widgets

== Step 1: Installation

1. Download the code from GitHub
2. Connect the display to the board
3. Upload the code to the GIGA

=== Folder structure

....
 GIGA_R1_dec18a.ino       => Arduino sketch folder
  ├── GIGA_R1_dec18a.ino  => main Arduino file
  ├── globals.h           => local library holding global variables
  ├── buttons.h           => local library to manage the buttons
  ├── meters.h            => local library to manage the meters
  ├── roller.h            => local library to manage the roller
  ├── title.h             => local library to manage the title label
  ├── arduino_secrest.h   => local library for WiFi credentials
  ├── thingProperties.h   => local library provided by Arduino
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {PUBLIC} License.

=== Contributing
To contribute to this project please contact: sgfpcb@gail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name                    | Part number | Quantity | Website
| A1 | GIGA R1                      | XXX         | 1        | https://www.arduino.cc/en/hardware#mega-family
| L1 | GIGA R1 Display Shield       | XXX         | 1        | https://www.arduino.cc/en/hardware#mega-family
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
